### ISSUE TITLE
VMware vSphere -VMs - Large infrastructure

### ISSUE THREAD

**Issue by digitaljedi2** [jorgedlcruz/vmware-grafana#8]
Is there any way to make the dashboard load all the panels, without trying to consume all the data?  

We have about 600 vm's, and this page takes forever to load, and eats up lots of memory (60GB) just to render.  Anyway to have this load without processing data unless a panel is clicked?

**Comment by jorgedlcruz** [comment]
Hello, it is a great Feature request, let me look of what I can do, maybe another option might be to select only the needed VMs, so the panel comes without any VM enabled, and maybe pagination will be great too. Let me check

**Comment by digitaljedi2** [comment]
Appreciate it.  Ideally we'd want to select a single vm, or two, and only have it load then.  Great work though!

**Comment by sunnybhatnagar** [comment]
Any help on this issue will be greatly appreciated. We are facing the same issue with 2000+ VM's.

**Comment by aimar-worth** [comment]
Same issue even with 100+ VM's. Other than that, great dashboards!

**Comment by jorgedlcruz** [comment]
Let me check what can I do with Influx or Grafana to limit the numbers of VMs showing at the same time guys, thanks so much for the feedback!

**Comment by jorgedlcruz** [comment]
I've uploaded a new Dashboard for the VMs section, I've minimized the panels, and order them alphabetically, not pagination at the moment, the other option is to show just one big panel, and when you pick the VMs from the drop down will appear inside the graph, as vSphere Client does really, thoughts?

**Comment by einhirn** [comment]
> the other option is to show just one big panel, and when you pick the VMs from the drop down will appear inside the graph, as vSphere Client does really, thoughts?

I thought about that, too... Of course a Graph with 450 VMs (in our case) will be very crowded, but maybe more performant than creating 4500 Panels expanded like before.

Maybe there is a way to incoorporate [The offset Clause](https://docs.influxdata.com/influxdb/v1.7/query_language/data_exploration/#the-offset-clause) into Grafana so that we can properly paginate the results whatever filters are active otherwise...

Also: Thinking of having to checkbox select some VMs from a list of 450 is rather cumbersome - I don't know yet whether Grafana supports using other variables in the query of one variable, because that would be great. Only other way I see is to allow direct editing of the regex in a textbox but I couldn't make that work yet.

**Comment by einhirn** [comment]
Just tried the new dashboard - much better.
Take a look at this - maybe you can make use of it? [Introducing Pagination for Grafana Scripted Dashboards](https://www.neteye-blog.com/2018/07/introducing-pagination-for-grafana-scripted-dashboards/)

**Comment by jorgedlcruz** [comment]
Hi guys, please try the latest Grafana v6.2, as it does include lazy load, meaning that it doesn't load the panels which are not visible, making the Dashboard work great, also if using Grafana v6.2, make sure you download the latest dashboard update, as it does make use of the new Bar Gauge Panel :)

**Comment by jorgedlcruz** [comment]
I hope now it does load better, I will close it, as I've seen it working with a couple of hundred VMs and thanks to the new lazy loading from Grafana 6.2, this works just great.

**Comment by tmihaldinec** [comment]
Hi,
i am not sure if this is related but i can only see 10VMs and i have 300+
Is there any way i can increase number of showed VMs per page?
thanks
t
